---
- name: restart nginx
  command: nginx -t
  notify: validated nginx restart

- name: reload nginx
  command: nginx -t
  notify: validated nginx reload

- name: validated nginx restart
  service:
    name: nginx
    state: restarted

- name: validated nginx reload
  service:
    name: nginx
    state: reloaded
