---
- name: dpkg configure
  shell: dpkg --configure -a

- name: Install aptitude using apt
  apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

- name: Install required system packages for Docker
  apt: name={{ docker_required_packages }} state=latest update_cache=yes

- name: Add Docker GPG key for ubuntu from official site
  apt_key:
    url: '{{ docker_gpg_url }}'
    state: present

- name: Verify gpg key with the fingerprint
  apt_key:
    id: 0EBFCD88
    state: present

- name: Add Docker repository
  apt_repository:
    repo: '{{ docker_repo }}'
    state: present
    update_cache: true

- name: Update apt packages
  apt:
    update_cache: true

- name: Install Docker
  apt: name={{ docker_packges }} state=present update_cache=true

- name: Update apt packages
  apt:
    update_cache: true

- name: Install Python Docker module
  pip:
    name: docker

- name: Add adminstrator to docker group
  user:
    name: '{{ admin_user }}'
    groups: docker
    append: yes

- name: Install Docker Compose
  get_url:
    url: '{{ docker_compose_url }}'
    dest: /usr/local/bin/docker-compose
    mode: u+x,g+x,o+x
